### ISSUE TITLE
interop with AngularDart components

### ISSUE THREAD

**Issue by aPaleBlueDot** [marcojakob/dart-dnd#22]
Hi,

First of all, kudos for making such a well thought out package.

After going through the dnd samples, I tried to use dnd capabilities on AngularDart Components but could get them to work. I'm a beginner in Dart, so I couldn't figure out why Chrome throws this error:

Uncaught TypeError: Cannot read property 'get$onMouseDown' of null
    at Object.J.get$onMouseDown$x (main.dart.js:81825)
    at _MouseManager.installStart$0 (draggable_manager.dart:313)

Any help would be much appreciated.  Below are snippets from respective .html, .dart and pubspec.yaml files from dart-lang/angular_components_example on github.

Kind regards,
aPaleBlueDot

{web/main.dart}
```
...
import 'dart:html';
import 'package:dnd/dnd.dart';

main() {
  bootstrapStatic(AppComponent, [/*providers*/], ng.initReflector);

  Draggable draggableA = new Draggable(querySelector('#draggable-a'),
      avatarHandler: new AvatarHandler.clone());

  Dropzone dropzone1 = new Dropzone(querySelector('#dropzone-1'),
      acceptor: new Acceptor.draggables([draggableA]));
}
```

{lib/src/material_expansionpanel_demo/material_expansionpanel_demo.html}

```
<div class="container">
  <div class="dropzone-container">
    <div  id="draggable-a" class="draggable">
      <p> Draggrable? </p>
    </div>
    <div  id="dropzone-1" class="dropzone">
      <material-expansionpanel-set >
        <material-expansionpanel name="Expansion panel">
          <div
            Oh hi. I was just trying not to take too much space here.
          </div>
        </ material-expansionpanel >
      </ material-expansionpanel-set >
    </div>
  </div>
</div>
```

{pubspec.yaml}

```
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'
dependencies:
  angular: 5.0.0-alpha+2
  angular_components: 0.9.0-alpha+2
  angular_forms: 1.0.1-alpha+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.1.0
  dnd: ^0.4.0
dependency_overrides:
  analyzer: ^0.31.0-alpha.1
dev_dependencies:
  webdriver: ^1.2.1
transformers:
- sass_builder
- angular:
    entry_points: web/main.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter
```
